### ISSUE TITLE
Rechercher la cause du plantage sur la recherche d'une clôture d'appel

### ISSUE THREAD

**Issue by tjpb92** [tjpb92/ExpCalls#31]
Rechercher la cause du plantage sur la recherche d'une clôture d'appel
Le plantage semble se passer toujours au même endroit

:point_right: Rajouter des traces pour y voir plus clair !
:point_right: Rajouter le nom de la table concernée lorsque l'on affiche un appel ou un essai

Voici les messages d'erreur : 
```
Aug 06, 2018 1:46:50 AM expcalls.ExpCalls_0572 processTickets
SEVERE: null
java.sql.SQLException: Could not do a physical-order read to fetch next row.
(-107)ISAM error: record is locked.
        at com.informix.jdbc.IfxSqli.errorDone(IfxSqli.java)
        at com.informix.jdbc.IfxSqli.receiveError(IfxSqli.java)
        at com.informix.jdbc.IfxSqli.receiveMessage(IfxSqli.java)
        at com.informix.jdbc.IfxSqli.sendStatementQuery(IfxSqli.java)
        at com.informix.jdbc.IfxSqli.executeStatementQuery(IfxSqli.java)
        at com.informix.jdbc.IfxSqli.executeStatementQuery(IfxSqli.java)
        at com.informix.jdbc.IfxResultSet.executeQuery(IfxResultSet.java)
        at com.informix.jdbc.IfxStatement.executeQueryImpl(IfxStatement.java)
        at com.informix.jdbc.IfxPreparedStatement.executeQuery(IfxPreparedStatement.java)
```
 :zap: **at bdd.FessaisDAO.setPartOfEOMResultSet(FessaisDAO.java:836)**  :boom:

```
        at bdd.FessaisDAO.setPartOfEOMPreparedStatement(FessaisDAO.java:513)
        at bdd.ClotureAppel.<init>(ClotureAppel.java:224)
        at expcalls.Ticket_0000.<init>(Ticket_0000.java:405)
        at expcalls.Ticket_0572.<init>(Ticket_0572.java:60)
        at expcalls.Ticket_0572.<init>(Ticket_0572.java:316)
        at expcalls.ExpCalls_0572.processTickets(ExpCalls_0572.java:93)
        at expcalls.ExpCalls_0572.<init>(ExpCalls_0572.java:45)
        at expcalls.ExpCalls.<init>(ExpCalls.java:82)
        at expcalls.ExpCalls.main(ExpCalls.java:120)
```

**Comment by tjpb92** [comment]
Voici deux nouveaux cas de figure : 

- Cas d'un appel verrouillé : 

```
août 08, 2018 5:10:56 PM expcalls.ExpCalls_0572 processTickets
GRAVE: null
java.sql.SQLException: Could not position within a table (test.fcalls).
(-107)ISAM error: record is locked.
	at com.informix.jdbc.IfxSqli.errorDone(IfxSqli.java)
	at com.informix.jdbc.IfxSqli.receiveError(IfxSqli.java)
	at com.informix.jdbc.IfxSqli.receiveMessage(IfxSqli.java)
	at com.informix.jdbc.IfxSqli.sendStatementQuery(IfxSqli.java)
	at com.informix.jdbc.IfxSqli.executeStatementQuery(IfxSqli.java)
	at com.informix.jdbc.IfxSqli.executeStatementQuery(IfxSqli.java)
	at com.informix.jdbc.IfxResultSet.executeQuery(IfxResultSet.java)
	at com.informix.jdbc.IfxStatement.executeQueryImpl(IfxStatement.java)
	at com.informix.jdbc.IfxPreparedStatement.executeQuery(IfxPreparedStatement.java)
	at bdd.PatternDAO.setSelectResultSet(PatternDAO.java:213)
	at bdd.FcallsDAO.setSelectPreparedStatement(FcallsDAO.java:525)
	at expcalls.ExpCalls_0572.processTickets(ExpCalls_0572.java:85)
	at expcalls.ExpCalls_0572.<init>(ExpCalls_0572.java:45)
	at expcalls.ExpCalls.<init>(ExpCalls.java:82)
	at expcalls.ExpCalls.main(ExpCalls.java:120)

```
- Cas d'un intervenant verrouillé : 

```
Ticket(1)=f99calls:{cnum=7493116, cuuid=e455f2bb-6b3b-3b86-5a17-a1565873f764, cseqno=32242, cunum=572, Cdate=2018-08-01 09:46:06.0, Ctime=09:46:06, Cname=pas de gardien, Ctel=06.18.20.34.60, Csympt=ECS ind elect/Le chauffe eau est mal fixé et va tombé., cc6num=3144853} bdd.Fcomplmt : {c6num=3144853, C6name=pertuisot, C6tel=06.18.20.34.60, c6int2=2, C6alpha1=XXXXXXXXXX}
août 08, 2018 5:10:56 PM expcalls.ExpCalls_0572 processTickets
GRAVE: null
java.sql.SQLException: Could not position within a table (test.ftoubib).
(-107)ISAM error: record is locked.
	at com.informix.jdbc.IfxSqli.errorDone(IfxSqli.java)
	at com.informix.jdbc.IfxSqli.receiveError(IfxSqli.java)
	at com.informix.jdbc.IfxSqli.receiveMessage(IfxSqli.java)
	at com.informix.jdbc.IfxSqli.sendStatementQuery(IfxSqli.java)
	at com.informix.jdbc.IfxSqli.executeStatementQuery(IfxSqli.java)
	at com.informix.jdbc.IfxSqli.executeStatementQuery(IfxSqli.java)
	at com.informix.jdbc.IfxResultSet.executeQuery(IfxResultSet.java)
	at com.informix.jdbc.IfxStatement.executeQueryImpl(IfxStatement.java)
	at com.informix.jdbc.IfxPreparedStatement.executeQuery(IfxPreparedStatement.java)
	at bdd.PatternDAO.setSelectResultSet(PatternDAO.java:213)
	at bdd.PatternDAO.setSelectPreparedStatement(PatternDAO.java:171)
	at expcalls.Ticket_0000.<init>(Ticket_0000.java:320)
	at expcalls.Ticket_0572.<init>(Ticket_0572.java:65)
	at expcalls.Ticket_0572.<init>(Ticket_0572.java:323)
	at expcalls.ExpCalls_0572.processTickets(ExpCalls_0572.java:93)
	at expcalls.ExpCalls_0572.<init>(ExpCalls_0572.java:48)
	at expcalls.ExpCalls.<init>(ExpCalls.java:82)
	at expcalls.ExpCalls.main(ExpCalls.java:120)
```
